// examples/ssg/src/App.vue
<script setup lang="ts">
import { ApiReference } from '@vektopay/api-reference'

import '@vektopay/api-reference/style.css'
</script>

<template>
  <div>
    <ApiReference
      :configuration="{
        url: 'https://registry.vektopay.com/@vektopay/apis/galaxy?format=json',
      }" />
  </div>
</template>

// examples/react-webpack/src/App.tsx
import { ApiReferenceReact } from '@vektopay/api-reference-react'
import React from 'react'
import '@vektopay/api-reference-react/style.css'

const App = () => {
  return (
    <ApiReferenceReact
      configuration={{
        url: 'https://registry.vektopay.com/@vektopay/apis/galaxy?format=yaml',
      }}
    />
  )
}

export default App
